apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop
  template:
    metadata:
      labels:
        app: eshop
    spec:
      containers:
        - name: eshop-app
          image: eshop-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/eshopdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Tkruoptlii@mysql36
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-service
spec:
  selector:
    app: eshop
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32370   # port accessible outside Kubernetes
  type: NodePort
